export default {
  // HOSTNAME: 'https://developer-games-back-318613.ew.r.appspot.com',
  HOSTNAME: 'http://localhost:4200',
  LOAD_TEAM_CHALLENGES_ENDPOINT: (teamId) => `/api/teamChallenges?teamId=${teamId}`,
  LOAD_ADMIN_TEMPLATE_CHALLENGES: (tournamentId) => `/api/teamChallenges/adminTemplates/${tournamentId}`,
  REGISTER_TEAM: '/api/teams',
  LOGIN: '/api/auth',
  LOAD_CHALLENGE_DETAIL: (challengeId) => `/api/teamChallenges/${challengeId}`,
  UPDATE_CHALLENGE: (challengeId) => `/api/teamChallenges/${challengeId}`,
  UPDATE_TEAM: (teamId) => `/api/teams/${teamId}`,
  LOAD_TOURNAMENT_TEAMS: (tournamentId) => `/api/teams?tournamentId=${tournamentId}`,
  EDIT_TEAM_PROFILE: '/api/profile/team',
  EDIT_ADMIN_PROFILE: '/api/profile/admin',
  CHECK_PASSWORD: '/api/auth/check',
  LOAD_TEAM: (teamId) => `/api/teams/${teamId}`,
  DELETE_PARTICIPANT: (participantId) => `/api/participants/${participantId}`,
  DELETE_TEAM: (teamId) => `/api/teams/${teamId}`,
  UPLOAD_AVATAR: (participantId) => `/api/upload/avatar/${participantId}`,
  UPLOAD_CHALLENGE_DELIVERABLE: (challengeId) => `/api/upload/deliverable/${challengeId}`,
  GET_COMPLETED_CHALLENGES: (tournamentChallengeId) => `/api/teamChallenges/completed/${tournamentChallengeId}`,
  LOAD_TOURNAMENT_CHALLENGES: (tournamentId) => `/api/tournamentChallenges?tournamentId=${tournamentId}`,
  CREATE_PARTICIPANT: '/api/participants',
  LOAD_TOURNAMENT: (tournamentName) => `/api/tournaments/${tournamentName}`,
  ACTIVATE_TOURNAMENT: (tournamentName) => `/api/tournaments/${tournamentName}/activate`,
};
