module.exports = {
  EMAIL_PARTICIPANT: 'EMAIL_PARTICIPANT',
  EMAIL_MENTOR: 'EMAIL_MENTOR',
  CREATE_PARTICIPANT: 'CREATE_PARTICIPANT',
  ACTIVATE_TOURNAMENT: 'ACTIVATE_TOURNAMENT',
  RESET_PASSWORD: 'RESET_PASSWORD',
};
