module.exports = {
  EMAIL_PARTICIPANT: 'EMAIL_PARTICIPANT',
  EMAIL_MENTOR: 'EMAIL_MENTOR',
  CREATE_PARTICIPANT: 'CREATE_PARTICIPANT',
  ACTIVATE_TOURNAMENT_START: 'ACTIVATE_TOURNAMENT_START',
  ACTIVATE_TOURNAMENT: 'ACTIVATE_TOURNAMENT',
  ACTIVATE_TOURNAMENT_ERROR: 'ACTIVATE_TOURNAMENT_ERROR',
  ACTIVATE_TOURNAMENT_END: 'ACTIVATE_TOURNAMENT_START',

  RESET_PASSWORD: 'RESET_PASSWORD',
};
