export default {
  ADD_TEAM_NAME: 'ADD_TEAM_NAME',
  ADD_PARTICIPANT: 'ADD_PARTICIPANT',
  SET_INPUT_VALUE: 'SET_INPUT_VALUE',
  SET_REGISTER_INPUT_VALUE: 'SET_REGISTER_INPUT_VALUE',
  IS_CHECKED_REGISTER_CONDITIONS: 'IS_CHECKED_REGISTER_CONDITIONS',
  SET_ENTRIES_WRONG_VALUES: 'SET_ENTRIES_WRONG_VALUES',
};
