export default {
  ADD_PARTICIPANT: 'ADD_PARTICIPANT',
  SET_TEAM_CHALLENGES_LOADING: 'SET_TEAM_CHALLENGES_LOADING',
  LOAD_TEAM_CHALLENGES_SUCCESS: 'LOAD_TEAM_CHALLENGES_SUCCESS',
  LOAD_TEAM_CHALLENGES_ERROR: 'LOAD_TEAM_CHALLENGES_ERROR',
  SET_ALERT_DATA: 'SET_ALERT_DATA',
  RESET_ALERT_DATA: 'RESET_ALERT_DATA',
};
